_format_version: "3.0"
_transform: true

services:
  - name: academic-service
    url: http://academic-service:3001
    routes:
      - name: academic-route
        paths:
          - /academic
        strip_path: true

  - name: payments-service
    url: http://payments-service:3002
    routes:
      - name: payments-route
        paths:
          - /payments
        strip_path: true

  - name: wellbeing-service
    url: http://wellbeing-service:3003
    routes:
      - name: wellbeing-route
        paths:
          - /wellbeing
        strip_path: true

plugins:
  - name: cors
    route: academic-route
    config:
      origins:
        - http://localhost:5173
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Correlation-Id
      exposed_headers:
        - X-Correlation-Id
      credentials: false
      preflight_continue: false
  - name: cors
    route: payments-route
    config:
      origins:
        - http://localhost:5173
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Correlation-Id
      exposed_headers:
        - X-Correlation-Id
      credentials: false
      preflight_continue: false
  - name: cors
    route: wellbeing-route
    config:
      origins:
        - http://localhost:5173
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Correlation-Id
      exposed_headers:
        - X-Correlation-Id
      credentials: false
      preflight_continue: false
